**1. Import the numpy package under the name**

In [ ]:
import numpy as np

**2. Print the numpy version and the configuration**

In [ ]:
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

**3. Create a null vector of size 10**

In [ ]:
F = np.zeros(10)
print(F)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. How to find the memory size of any array**

In [ ]:
F = np.zeros((10,10))
print("%d bytes" % (F.size * F.itemsize))

800 bytes


**5. Create a null vector of size 10 but the fifth value which is 1**

In [ ]:
F = np.zeros(10)
F[4]=1
print(F)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**6. Create a vector with values ranging from 10 to 49**

In [ ]:
F = np.arange(10,50)
print(F)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
F = np.arange(9).reshape(3,3)
print(F)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [ ]:
F = np.nonzero([1,2,0,0,4,0])
print(F)

(array([0, 1, 4]),)


**9. Create a 10x10 array with random values and find the minimum and maximum values**

In [ ]:
F = np.random.random((10,10))
Fmin, Fmax = F.min(), F.max()
print(Fmin,Fmax)

0.00047332929110488475 0.9898628012810118


**10. Create a random vector of size 30 and find the mean value**

In [ ]:
F = np.random.random(10)
r = F.mean()
print(r)

0.42021380038072015


**11. Create a 2d array with 1 on the border and 0 inside**

In [ ]:
F = np.ones((10,10))
F[1:-1,1:-1] = 0
print(F)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**12. How to add a border (filled with 0's) around an existing array?**

In [ ]:
Z = np.ones((5,5))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**13. What is the result of the following expression?**

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**14. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**15. Create a checkerboard 8x8 matrix using the tile function**

In [ ]:
F = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(F)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**16. Normalize a 5x5 random matrix**

In [ ]:
F = np.random.random((5,5))
F = (F - np.mean (F)) / (np.std (F))
print(F)

[[ 1.80369064  1.12030665  1.32046865 -0.410323    0.67953901]
 [-1.16537876 -0.36712433  0.05491947  1.12492531  0.87629999]
 [-1.2562655  -1.04561849  1.45317202 -0.80077157 -0.73251507]
 [ 1.21032839 -1.115437   -1.10079364  1.15092763 -0.66453242]
 [-0.97237879 -0.79247761  0.19139704 -1.0467362   0.48437759]]


**17. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [ ]:
F = np.dot(np.ones((5,3)), np.ones((3,2)))
print(F)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**18. What is the output of the following script?**

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


**19. What are the result of the following expressions?**

In [ ]:
np.array(0) / np.array(0)  #RuntimeWarning: invalid value encountered in true_divide np.array(0) / np.array(0)
np.array(0) // np.array(0) #RuntimeWarning: divide by zero encountered in floor_divide np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)  #array([0.])

<ipython-input-24-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-24-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

**20. How to round away from zero a float array ?**

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[ -3.   1.  -8.  -3.   2.   2. -10.   1. -10.  -2.]


**21. How to find common values between two arrays?**

In [ ]:
F1 = np.random.randint(0,10,10)
F2 = np.random.randint(0,10,10)
print(np.intersect1d(F1,F2))

[0 2 7 9]


**22. How to ignore all numpy warnings (not recommended)?**

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

**23. How to get the dates of yesterday, today and tomorrow?**

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2023-07-22
2023-07-23
2023-07-24


**24. How to compute ((A+B)*(-A/2)) in place (without copy)?**

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

**25. Consider a generator function that generates 10 integers and use it to build an array**

In [ ]:
def generate():
    for x in range(10):
        yield x


Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**26. How to sum a small array faster than np.sum?**

In [ ]:
F = np.random.random(10)
np.add.reduce(F)

2.7603373435887115

**27. Consider two random array A and B, check if they are equal**

In [ ]:
A = np.random.randint(2,3,5)
B = np.random.randint(2,3,5)

equal = np.array_equal(A,B)
print(equal)

True


**28. Make an array immutable (read-only)**

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1    #assignment destination is read-only

**29. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.56571073 0.3450975  1.08988685 0.92636694 0.7963969  0.85016947
 0.68498748 1.15109374 0.73984221 1.15227768]
[1.47370825 0.84187125 0.43722254 0.27105104 1.25576479 1.41403762
 0.35009431 0.65186911 0.95977493 1.03361065]


**30. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))**

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

**31. How to print all the values of an array?**

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((15,15))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**32. Consider a random vector with shape (100,2) representing coordinates, find point by point distances**

In [ ]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((5,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.49940161 0.55642901 0.64377104 0.49261076]
 [0.49940161 0.         0.69090197 0.19092527 0.71600872]
 [0.55642901 0.69090197 0.         0.88120934 0.11778268]
 [0.64377104 0.19092527 0.88120934 0.         0.90653368]
 [0.49261076 0.71600872 0.11778268 0.90653368 0.        ]]
[[0.         0.35638861 0.8928077  0.48848129 0.45982193]
 [0.35638861 0.         0.85518719 0.13978584 0.15171117]
 [0.8928077  0.85518719 0.         0.92954908 0.74609909]
 [0.48848129 0.13978584 0.92954908 0.         0.1834511 ]
 [0.45982193 0.15171117 0.74609909 0.1834511  0.        ]]


**33. How to convert a float (32 bits) array into an integer (32 bits) in place?**

In [ ]:
F = (np.random.rand(10)*100).astype(np.float32)
A = F.view(np.int32)
A[:] = F
print(A)

[68 26 63 23 26 28 82 29 59  0]


**34. What is the equivalent of enumerate for numpy arrays?**

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**35. Generate a generic 2D Gaussian-like array**

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

**36. Subtract the mean of each row of a matrix**

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.3941308   0.30455914  0.38641689  0.02425794 -0.02054404 -0.28126934
   0.21174278 -0.0537049   0.02152243 -0.1988501 ]
 [-0.03118089 -0.3646578   0.40704999 -0.05844858  0.09211783 -0.21816688
   0.19871703  0.41927101  0.06525933 -0.50996104]
 [ 0.37159463 -0.13716422  0.13855093 -0.37931476  0.34178653  0.34231272
  -0.31081111 -0.11256334 -0.39791265  0.14352127]
 [-0.03275663 -0.24465768  0.14404086 -0.35211066  0.22543277  0.05856469
  -0.25155117  0.44874589  0.36517301 -0.36088109]
 [ 0.38638039 -0.14194451  0.0335144   0.21502091 -0.16209085 -0.28201182
   0.20110439 -0.19395966  0.22726722 -0.28328047]]


**37. How to sort an array by the nth column?**

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 2 2]
 [9 7 7]
 [5 1 7]]
[[5 1 7]
 [2 2 2]
 [9 7 7]]


**38. How to tell if a given 2D array has null columns?**

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


**39. Find the nearest value from a given value in an array**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5013048062395883


**40. Create an array class that has a name attribute**

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


**41. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?**

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


**42. Considering a four dimensions array, how to get sum over the last two axis at once?**

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[66 57 47 49]
 [49 46 44 42]
 [41 43 55 60]]
[[66 57 47 49]
 [49 46 44 42]
 [41 43 55 60]]


**43. How to get the diagonal of a dot product?**

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))


np.sum(A * B.T, axis=1)



array([1.23834585, 0.92892745, 0.84123452, 0.92008144, 1.41551641])

**44. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**45. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**Broadcasting**

In [2]:
import numpy as np

array1 = np.array([1,2,3,4])
array2 = np.array([1,2,3])

sum = array1 + array2

print(sum)


# this code contain broadcasting error because arrays are not in same dimensions

ValueError: ignored

In [10]:
import numpy as np

arr1 = np.array([2,3])
print('Shape of array 1 is: ', arr1.shape)

arr2 = np.array([[1,2],[3,4],[5,6]])
print('Shape of array 2 is: ', arr2.shape)

sum = arr1 + arr2

print(sum)


#this code run smoothly beacuse in array 1
#we have a shape of (2,1) so that it can expand it easily

Shape of array 1 is:  (2,)
Shape of array 2 is:  (3, 2)
[[3 5]
 [5 7]
 [7 9]]


In [29]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])


arr2 = np.array([[1,2],[3,4],[5,6]])
print('Shape of array 2 is: ', arr2.shape)

# result_shape = (max(arr1.shape[0], arr2.shape[0]), max(arr1.shape[0],arr2.shape[0]))
# result = np.zeros(result_shape, dtype=arr1.dtype)

# for i in range(result_shape[0]):
#   for j in range(result_shape[1]):
#     result[i, j] = arr1[i % arr1.shape[0], j % arr1.shape[1]] + arr2[i % arr2.shape[0], j % arr2.shape[1]]



# print(result)


newArr = np.array([[4,5]])

arr1 = np.vstack((arr1 , newArr))
print('Shape of array 1 is: ', arr1.shape)

addition = arr1+arr2
print(addition)

Shape of array 2 is:  (3, 2)
Shape of array 1 is:  (3, 2)
[[ 2  4]
 [ 6  8]
 [ 9 11]]


In [22]:
#result_shape[0]

3